name: Déploiement Continu Alwaysdata

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Déploiement vers le serveur
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code actuel
        uses: actions/checkout@v4

      - name: Synchronisation sécurisée via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './*'
          remote_path: 'www'
          sftp_only: true